artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://www.cs.toronto.edu/~kriz/cifar-100-python.tar.gz
  local_data_file: artifacts/data_ingestion/data.tar.gz
  unzip_dir: artifacts/data_ingestion

data_generation:
  base_dir: artifacts
  root_dir: artifacts/transformed_data
  train_file: artifacts/data_ingestion/cifar-100-python/train
  test_file: artifacts/data_ingestion/cifar-100-python/test
  meta_file: artifacts/data_ingestion/cifar-100-python/meta
  transformed_data_path: artifacts/transformed_data/train_val_data
  metadata_path: artifacts/transformed_data/metadata

generator:
  root_dir: artifacts/transformed_data
  transformed_data_path: artifacts/transformed_data/train_val_data
  metadata_path: artifacts/transformed_data/metadata
  train_file: artifacts/data_ingestion/cifar-100-python/train
  test_file: artifacts/data_ingestion/cifar-100-python/test
  meta_file: artifacts/data_ingestion/cifar-100-python/meta

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5

prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.h5

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5


